### ISSUE TITLE
Define Project Standard for Property Order

### ISSUE THREAD

**Issue by roblarsen** [h5bp/main.css#16]
see #15 (which may close this)

The options are alphabetical or by type? Is there some other option that people use?

**Comment by mattbrundage** [comment]
I'm not aware of any other widely-used conventions.

In my collaborative and solo projects, I always default to ordering properties alphabetically, as the alphabet has a universally understood order.

Whenever I encounter other styles, I first have to determine if it's by type, or just random (no order). If it's by type, then I have to determine if it's ordered alphabetically in each of the four/five types, or just random.

So to me, ordering by type introduces additional cognitive load that I'd rather avoid.

**Comment by coliff** [comment]
A few interesting points / links:

- Google's CSS Style Guide says to put them in alphabetical order:
https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order

- AirBnbs CSS Guide doesn't specify precisely:
https://github.com/airbnb/css#ordering-of-property-declarations

- Idiomatic CSS says smaller teams may prefer to cluster related properties (e.g. positioning and box-model) together whereas larger teams may prefer the simplicity and ease-of-maintenance that comes with alphabetical ordering. (https://github.com/necolas/idiomatic-css#declaration-order)

- A while back CSS tricks ran a poll on this; and most people said they sorted by type (45%) and 14% sorted alphabetically. (https://css-tricks.com/poll-results-how-do-you-order-your-css-properties/)

At this point, I think I'd vote for alphabetical since it's the easiest to understand, and plus I tend to agree with everything else on the Google CSS Style guide.

**Comment by roblarsen** [comment]
Closed via #15

**Comment by roblarsen** [comment]
Alphabetical works for me.
