### ISSUE TITLE
sr-only > visually-hidden ?

### ISSUE THREAD

**Issue by roblarsen** [h5bp/main.css#82]
See the @nickcolley  comment on #27 [rename visuallyhidden to sr\-only by coliff · Pull Request \#27 · h5bp/main\.css](https://github.com/h5bp/main.css/pull/27)

**Comment by coliff** [comment]
👍  I agree with the reasoning. I suggest that the class should be `visually-hidden` rather than `visuallyhidden`. Separating words with a hyphen has a few advantages, won't be flagged as a typo by spell checkers and is easier to read/parse at a glance.
The `visually-hidden` class name is used by Bootstrap v5 and the a11y project too.
https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/
https://v5.getbootstrap.com/docs/5.0/helpers/visually-hidden/
